apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGhkYThia3ow
  CLOUDINARY_KEY: MjY4ODEyMzEzOTQ1Nzc4
  CLOUDINARY_SECRET: SWpQMG5kaDBIbkZvbTVDazkxaG5zVk9Tb0U0
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZV0ppWVhOemFHRnBhemN6T1NJc0ltRWlPaUpqYlcxb2MzbzBNMkl3Y21kbk1uQnpObkk1YzJveE4yOXNJbjAuNHZ3cEhMd2hXaGktbWptWEhWWUMzdw==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAubXUzd2VsdS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
  
